# Generated by Django 3.1.4 on 2020-12-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='duration',
        ),
        migrations.AlterField(
            model_name='sample',
            name='sound',
            field=models.FileField(upload_to=None),
        ),
    ]
