# Generated by Django 3.1.4 on 2020-12-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpler', '0003_auto_20201217_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='artist',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='sound',
            field=models.FileField(upload_to='sounds/wav/'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
