# Generated by Django 3.1.4 on 2020-12-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpler', '0004_auto_20201217_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sound',
            field=models.FileField(upload_to='media'),
        ),
    ]
