# Generated by Django 3.1.4 on 2020-12-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpler', '0005_auto_20201217_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sound',
            field=models.FileField(upload_to='media/'),
        ),
    ]
