# Generated by Django 3.1.4 on 2020-12-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpler', '0006_auto_20201218_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sound',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
