# Generated by Django 3.1.4 on 2020-12-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpler', '0007_auto_20201218_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
